### ISSUE TITLE
JS source files should be included by default

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/silverstripe-admin#1053]
Currently these files are excluded by default.

We've enabled users to inject over them through the injector but it's common for users to extend these components, make small changes, then inject over them which is not possible with a default composer install

This also impacts automated build systems which will need to run `composer install --prefer-source` to build any project that has these kinds of components

The negative impacts I can think of would be increasing the size of the composer dependency by now including these JS files and increasing the chances that updating these components creates breaking changes for projects.

I'm happy to start making some PR's but I would like to first get everyone on the same page and agree to the change going forwards and which release we could make the change in (selfishly I'd like to add it to 4.5 as a minor patch but can see why we'd want to make it happen in a future minor release)

Thoughts, feelings?

**Comment by blueo** [comment]
something to consider is that this pattern may be more common in class based react components. It may change as react shifts more towards functional components with hooks etc.

**Comment by chillu** [comment]
Can you solve this by requiring those modules to be checked out via `type=vcs` rather than `type=dist` in composer? Alternatively, can you run some stats on how much extra network transfer a standard `composer create-project silverstripe/installer` would be with this change?

**Comment by blueo** [comment]
that's a good idea - we can certainly give it a whirl.

**Comment by ScopeyNZ** [comment]
> stats on how much extra network transfer a standard `composer create-project silverstripe/installer`

Should we really be concerned about this metric over actually making our intended JS API consumable?

I'm still of the opinion we need to figure out an NPM offering to properly fix this.

**Comment by blueo** [comment]
just an update on using composer to set the install type. Unless you're referencing a commit and using a repository config (with type="vsc" or type="git") then composer will grab the dist version of the package. So it doesn't work well for when you want to include the src files for a package that is not a fork etc. 

I also tried the `preferred-install` config option, that will be overridden by the cli argument `--prefer-dist` which is not ideal as lots of CI configs use this.

**Comment by Cheddam** [comment]
Thoughts on the NPM approach:

- We'd need to expand Cow's tooling to release NPM packages alongside module tags, else this would be a major increase in toil.
- This still wouldn't result in source JS being provided in dist bundles, and I assume we would still bake in the dist JS to avoid introducing a hard dependency on NPM.
- Developers wanting to consume these NPM packages would need to be careful to keep the versions in sync with their equivalent Composer modules, otherwise risking incompatibility between their extended components and the pre-baked core JS.

This isn't to say the NPM approach doesn't make sense in the longer term (5.x?), but in the short term, I'm in favour of including source JS in dist bundles. The proposed workaround of consuming the source versions of these modules is a lot heavier, given it'll also fetch git data and any other files we currently exclude from dist bundles, and as @blueo has found, it's difficult to invoke anyway.

**Comment by Cheddam** [comment]
Is there any strong opposition to proceeding with this change? I think it'd be good to get into the 4.7 release so that developers can stop working around it while we find a longer term solution.

cc/ @chillu @ScopeyNZ @maxime-rainville

**Comment by maxime-rainville** [comment]
Yeah ... it can sucks that we would force a bunch of projects to download these source files for nothing, but if you're trying to customise the admin area, there's not really a way around it.

**Comment by chillu** [comment]
I'm not keen on the NPM approach due to maintainability concerns. You have to remember that this is very much early adopter territory, we're optimising this for a handful of devs who are deeply customising the CMS UI like this. Early adopters should also have good experiences, but if it's a matter of knowing you need to run `composer install --prefer-source` then I think that's an acceptable limitation for now.

So in the worst case of `silverstripe/admin/`, this will increase the dist size from around 3.7MB to 5.0MB. Other modules will be less affected. If there's really no way to get composer to check out from src during a `composer install` unless it's a fork or a custom `repositories` entry, then I'd be OK changing the `.gitarchive` flags in the repos.

Here's how `--prefer-source` is described on https://getcomposer.org/doc/03-cli.md#install-i

> -prefer-source: There are two ways of downloading a package: source and dist. For stable versions Composer will use the dist by default. The source is a version control repository. If --prefer-source is enabled, Composer will install from source if there is one. This is useful if you want to make a bugfix to a project and get a local git clone of the dependency directly.

**Comment by Cheddam** [comment]
A 1.3MB increase in the dist size of a module _at worst_ is much less painful than a ~50MB increase in size for installing it with `--prefer-source`. If you expand that out to comparing a standard `silverstripe/installer` project installed with `--prefer-dist` vs. `--prefer-source`, it's even more stark: 50MB vs **600MB**.

If we're not going down the NPM path (which I'm totally fine with), I think this change has to happen - customising the CMS in this way can't remain an 'early adopter' edgecase forever.

**Comment by chillu** [comment]
Yeah the fact that you can't *selectively* use `--prefer-source` on deps is the killer. I'm fine with removing `client/*` from [.gitattributes](https://github.com/silverstripe/silverstripe-admin/blob/1/.gitattributes#L12)

**Comment by Cheddam** [comment]
@silverstripe/core-team Can we get some thumbs up/down on this?

**Comment by sminnee** [comment]
It seems like a sensible trade off to include src/ in the export bundles
