### ISSUE TITLE
Fix breakages related to Reactstrap 8 upgrade

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-admin#1126]
### Overview
A PR was recently merged to upgrade the version of Reactstrap. Expectedly, this has caused a number of regressions in the dev branch that need to be resolved.

@maxime-rainville has done an initial review and found that the following components are broken:
- Readonly HiddenField
- Readonly CheckboxSetField
- LookupField
- Readonly HTMLEditorField
- Readonly Single Select 

[See Pattern Library](https://silverstripe.github.io/silverstripe-admin/).

### ACs
- [x] All components in the Pattern Library render as expected 
- [x] All components mentioned in the [comment](https://github.com/silverstripe/silverstripe-admin/issues/1126#issuecomment-701835393) have a unit test written 
- [ ] ~Identify failing builds that are likely to be as a result of this change and resolve issues - is Elemental failing? **(Steve: have written a comment below)~**
- [x] Re-run CI builds for modules believed to be affected, currently assumed to be affected:
  - asset-admin, campaign-admin, versioned-admin. **Ditto**
- [ ] ~Stretch goal: all comments mentioned in the above comment have been added to the storybook/ pattern lib **(Steve: have written a comment below)~**

### Notes
- Remember, when possible if there are no jest tests for the component start a basic one to check that the component renders

### PRs
- [x] https://github.com/silverstripe/silverstripe-behat-extension/pull/195
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2594
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1128

### Rerunning travis on dev branch of modules:
- [x] elemental - https://travis-ci.org/github/dnadesign/silverstripe-elemental/builds/732139280
- [x] asset-admin -- behat failure todo with I think `ImageSizePresetList.js` not getting auto populated - https://travis-ci.org/github/silverstripe/silverstripe-asset-admin/jobs/733457346 - https://s3.amazonaws.com/silverstripe-travis-artifacts/silverstripe/silverstripe-asset-admin/733457343/733457346/screenshots/insert-an-image.feature_23.png
- [x] campaign-admin
- [x] versioned-admin - https://travis-ci.org/github/silverstripe/silverstripe-versioned-admin

### PRs after 1128 is merged:
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/178 << green and ready for merge

### Follow up
 - [x] [Dropdown actions don't respond to "enter" key #1067](https://github.com/silverstripe/silverstripe-admin/issues/1067)

**Comment by brynwhyman** [comment]
cc @silverstripeux

**Comment by sachajudd** [comment]
@maxime-rainville I can test these once fixed if need be to ensure nothings missing.

**Comment by brynwhyman** [comment]
Related: https://github.com/silverstripe/silverstripe-admin/issues/1067

**Comment by emteknetnz** [comment]
I've identified the following admin and asset-admin components that are missing either unit-tests or storybook, so we'll need to do something here

# silverstripe-admin

## Components
1) Accordion
2) FieldGroup
3) Focusedzone
4) HeaderField
5) HtmlEditorField
6) InputField
7) LabelField
8) LiteralField
9) MobileMenuToggle
10) NotFoundComponent
11) Preview
12) ResizeAware
13) Toolbar

## Containers
14) ToastsContainer


# silverstripe-asset-admin

## Components

## Containers
15) HistoryList
16) InsertMediaModal
17) MoveModal

**Comment by emteknetnz** [comment]
>> Identify failing builds that are likely to be as a result of this change and resolve issues - is Elemental failing?

I think we're better to worry about this AFTER merging the related PRs on this issue.

Reactstrap is used at the component level and that's we're testing and fixing things at the component level in this PR.

If something reactstrap related is broken in a module such as Elemental, then the way to fix it is to first merge the bugfixes in the related PRs on this issue, and then rebuild the javascript in the broken module which will apply the bugfixes.

**Comment by emteknetnz** [comment]
>> Stretch goal: all comments mentioned in the above comment have been added to the storybook/ pattern lib

I'm not sure this is altogether worthwhile, at least not on this issue.  The reason being is that the majority of components are currently not in the pattern library, and the components identified in this issue are only a subset of those components.

Pattern library was only mentioned in relation to regression testing because you'll see a large red warning in the pattern library if something has a regression.  It's effectively a less efficient form of regression testing then a regular, automated unit-tests, though still faster then having to write a new unit-test where there is no coverage.

Adding components properly to the pattern library includes thinking about the various permutations that a component has, and adding 'knobs' which allow the user to view these different permutations.  This isn't really in scope for this regresssion testing which is really more along the lines of "it renders".

I think it's actually worthwhile backfilling the pattern library, then, rather than attempting to do it as a stretch goal, which is effectively just scope creep in this context, I'd recommend that we split this off as a separate issue and properly estimate and prioritise.  This new issue would be pretty easy to split into multiple issues to tackle a subset of components at a time if we felt it was sized too large.

**Comment by dnsl48** [comment]
> All components in the Pattern Library render as expected

@sachajudd would you like to have a look the pattern library and just check we didn't mess it up? :)

**Comment by dnsl48** [comment]
> Stretch goal: all comments mentioned in the above comment have been added to the storybook/ pattern lib (Steve: have written a comment below)

The components missing from the storybook are captured in the other issue:
https://github.com/silverstripe/silverstripe-admin/issues/1137

**Comment by sachajudd** [comment]
Yup looking all good @dnsl48
