### ISSUE TITLE
Validation warning icon broken in Firefox

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-admin#1130]
### Overview
[Recently implemented](https://github.com/silverstripe/silverstripe-admin/pull/1111) validation warning icons are not displaying in Firefox correctly:

![image](https://user-images.githubusercontent.com/15868440/95028111-6883f080-06fa-11eb-95b7-8171598b3744.png)

### Versions:
silverstripe/admin 1.6.2

### Replication steps
You'll need to create a custom field with a validation rule. [Replication steps in the previous PR](https://github.com/silverstripe/silverstripe-admin/pull/1111#issuecomment-694613669)

**Comment by brynwhyman** [comment]
Raising on behalf. Will come back with more details

**Comment by jareddreyerss** [comment]
Affected on:
Firefox (81.0.1) with macOS High Sierra (10.13.6)

**Comment by Cheddam** [comment]
This may be related to an issue we previously thought fixed - that the addition of new icons doesn't change the URL of the font files, meaning browsers may continue to cache the old version.

[The fix for this](https://github.com/silverstripe/webpack-config/pull/47) didn't make it into a `@silverstripe/webpack-config` release until [a couple of weeks ago](https://github.com/silverstripe/webpack-config/releases/tag/1.7.0), so the version used in admin may not yet contain it, leading to the regression in behaviour.

**Comment by Cheddam** [comment]
This should be fixed by #1133, which has been released as `silverstripe/admin 1.6.3`.
