### ISSUE TITLE
Add more options dropdown to asset bulk actions

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#128]
Asset bulk actions should/could include options:
Move
Delete 
Add to campaign
Unpublish 
Publish
Archive
Download

See designs https://projects.invisionapp.com/boards/2JX68PNPDF6K/

**Comment by chillu** [comment]
I've replaced this with three more focused cards in the asset-admin repo:
https://github.com/silverstripe/silverstripe-asset-admin/issues/523
https://github.com/silverstripe/silverstripe-asset-admin/issues/524
https://github.com/silverstripe/silverstripe-asset-admin/issues/525

Note that I haven't created cards for "archive" or "download", since I don't see a need for that (we won't get around to it anytime soon). The "delete" feature was already implemented

**Comment by sminnee** [comment]
I assume that "delete" is actually "archive"?

**Comment by kinglozzer** [comment]
If someone was considering picking up the “download” feature, should the action trigger:

- A ZIP download of all the selected assets/directories (Flysystem can do this IIRC)
- Individually triggered downloads for the selected assets (and those contained in selected directories)

My instinct tells me the first option is the best one if multiple assets are selected, I don’t know if we need to worry about memory usage though?

**Comment by kinglozzer** [comment]
Okay so we’d also need to consider `ext-zip` support to offer a ZIP download option. Perhaps it could be a module (assuming the React UI is extensible enough, I haven’t touched client-side code yet 😄)
