### ISSUE TITLE
System files are not protected in the files area

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#163]
## ACs
* System files are not moved to the assets area when sites are migrated from SS3 to SS4

Seems dangerous to have system files in the files area and not have them protected (I deleted them, can't remember what they were so no screenshot - 404.html or something). Would be good to confirm this is an issue. If so we might need to design a pattern to protect these files.

TASKS
* [x] Update migration script to exclude disallowed file types

PR
- [x] https://github.com/silverstripe/silverstripe-assets/pull/61
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7329

**Comment by flamerohr** [comment]
I wouldn't label this an enhancement, it would seem that this could be a potential security issue...

**Comment by dhensby** [comment]
I'm not sure there are any system files in the assets area.

the static export of the error pages (eg: error-404.html) are kept in the assets dir because it's one we can be sure is writeable by the webserver, but deleting it is not a security issue nor a functional one (it won't break the site if it's gone).

Rather than blacklisting files named `error-*.html` we should look into the possibility of naming it `.error-*.html` and having dot files ignored by the assets system

**Comment by clarkepaul** [comment]
Remove files on migration from 3.0 with a script. @tractorcow can explain a bit more.

**Comment by tractorcow** [comment]
It looks like migrated files from ss3.0 can have these system files included. We can have a filter that prevents this migration script including those files.

**Comment by chillu** [comment]
Given that this is going to be visible for every migrated site, and has the potential to confuse CMS authors browing a high profile section, I'm raising impact to medium. It's also best handled *before* the stable release, in terms of adding this to the migration script. I'm assuming it's going to be a quick fix.
