### ISSUE TITLE
SPIKE Do a POC for replacing `redux-form` with `react-hook-form`

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-admin#1747]
Follow-up from https://github.com/silverstripe/silverstripe-admin/issues/1711 after [an architecture discussion](https://silverstripe.atlassian.net/wiki/spaces/PD/pages/3270574085/2024-05-15+Architecture+catch-up) about it.

## Notes from the architecture discussion
- React final form not really any useful.
- Three potential approaches
    - Move away from Redux, refactor form builder and adopted an a library
        - Very complex, very risky
    - Do the bare minimum, stick with Redux and maybe use react-hook-form, try not to touch form schema too much.
    - Do nothing, suffer with Redux-form for now
- 2 day spike to see how far we could go with react-hook-form. 

## Timebox
3 days to get as far as you can

## Objectives of the SPIKE
- Understand the level of difficulty in replacing `redux-form` with `react-hook-form`
- Make a recommendation as to whether we should proceed with replacing `redux-form` for CMS 6 or kick the can down the proverbial road

## PRs
- https://github.com/silverstripe/webpack-config/pull/74
- https://github.com/silverstripe/silverstripe-admin/pull/1754
- https://github.com/silverstripe/silverstripe-elemental/pull/1195

**Comment by emteknetnz** [comment]
I've made very good progress replacing redux-form with react-hook-form, I highly recommend we continue this work

The linked PRs above go a very long way with the replacement. FormBuilder now uses react-hook-form and it will correctly submit formschema powered forms and handle validation correctly e.g. asset-admin File details form, LinkField. I've also gotten elemental inline editing working correctly which was a trickey one because it relied on "remote-submitting" forms as the inline save button is not part of the same tree as the inline-form.

Some things still todo:
- Remove/refactor a bunch of places where 'redux-form' is imported in silverstripe/admin - we're still using redux-form helper methods used to update the redux store. When that's done remove redux-form from package.json
- There's a yarn warning about 'providerValue' on Form.js every render, and recommends using a useMemo() hook - would require refactoring Form.js as a functional component in order to use the hook - that should be fairly easy
- Elemental TextCheckboxGroupField isn't rendering correctly because cannot set the noHolder prop correctly because children is no different because of the use of `<ReactHookFormContext.Consumer>` on FormBuilder.js - solution is to refactor FormBuilder to a functional component so can use useContext() at top of component instead of in  mapFieldsToComponents(), though this is non-trivial due to the use of the withInjector() HOC on it populating this.context.
- Elemental has a handleFormInit / onFormInit thing that hasn't been refactored - means that setFormHasRendered() hook is currently non-functional
- Run it across kitchen-sink CI
