### ISSUE TITLE
Modal success animation extends outside of the modal

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#345]
The animation of the success message should not extend outside of the modal when adding an item to a campaign.

![add-to-campaign-bug](https://user-images.githubusercontent.com/555033/32474154-098f5b8e-c3d0-11e7-9437-436ccb2d69b9.gif)

## PR
- [ ] silverstripe/silverstripe-admin#601

**Comment by chillu** [comment]
I don't see what you mean based on the screenshot - can you clarify?

**Comment by clarkepaul** [comment]
Its a gif, need patience (pretty slow), hopefully you'll see the success notification at the end after adding item to the campaign.

**Comment by dhensby** [comment]
> Its a gif, need patience (pretty slow), hopefully you'll see the success notification at the end after adding item to the campaign.

it's still not completely clear :/

**Comment by kinglozzer** [comment]
I’m guessing the overflow here is the issue? It should probably just appear inside the modal rather than animate up from below/outside it:

<img width="409" alt="screen shot 2017-11-22 at 16 20 14" src="https://user-images.githubusercontent.com/1655548/33137908-12783f18-cfa1-11e7-993f-6355f8f9f00b.png">
