### ISSUE TITLE
SS4: ModelAdmin shows blank page when search with single result is clicked

### ISSUE THREAD

**Issue by axllent** [silverstripe/silverstripe-admin#410]
This happens in both 4.0.1 and 4.0.2 (unsure about 4.0.0)

Sorry but it is difficult to describe this bug and it has taken a while to track down a scenario where it happens and is reproducible.

Basically if you have a ModelAdmin that contains multiple results, search for something that produces a **single** search result. When you click that result you get a blank page (no JS errors). I can always get it in some instances, and others not, so I'm not sure if it is relative to the number of objects being displayed. In my case I have just 16 pages.

To provide a working scenario, take the following ModelAdmin as a test:

```php
<?php
use SilverStripe\Admin\ModelAdmin;
class TestModelAdmin extends ModelAdmin
{
    private static $menu_title = 'Broken Search';
    private static $url_segment = 'broken-search';
    private static $managed_models = [
        'SilverStripe\CMS\Model\SiteTree'
    ];
}
```
Now in the CMS, go to /admin/broken-search/ and search for "page not" (which should hopefully produce one result, eg: the `Page not found` page). Click that result = blank page / frame.

I've tested this on both Firefox and Chrome, bot with the same result, so I hope you can reproduce this too :-)

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/435

**Comment by unclecheese** [comment]
Have research this bug and found that it only happens when there are spaces in the search term. On list view, spaces are properly expressed with a `+` sign (`?q%5BTitle%5D=page+not`), but in detail view, that `+` sign gets replaced with its hex equivalent `%2B`, which is too eager. Plus signs are valid in URLs. This causes the search term to be interpolated into the query incorrectly ('page+not' instead of 'page not'), and a record of the given ID cannot be found in the list due to that filter that never matches, and the request redirects back and dies.

The culprit is the `addSearchParams` method in `sspath.js`, a library from 2011. This function calls `$.param`, a native jquery method for turning objects into parameter strings. Patching the native jquery method would be too aggressive, so the `addSearchParams` will be updated to undo `+` replacination after `$.params` is called.
