### ISSUE TITLE
Form fields should have a consistent width 

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-admin#417]
Form fields should have the same width, currently at different resolutions some fields have a different width.

Seems to be chosen select dropdowns and multi-select which I'm guessing will be phased out so perhaps not a pressing issue?

![image](https://user-images.githubusercontent.com/555033/35603091-7d3cfc90-06a0-11e8-8f04-4947a32a8ee1.png)

**Comment by sachajudd** [comment]
Also inconsistent with these readonly fields seen in Userforms
![image](https://user-images.githubusercontent.com/24258161/35659795-15560644-076d-11e8-8ed1-3b0b346dd412.png)

**Comment by dhensby** [comment]
I'd also suggest the current widths are too large at the moment - they feel unnaturally wide when looking at them on big screens. I think we should apply the same kind of restrictions on widths of form fields as we would for paragraphs (50 - 75 characters, ideally) - we can probably push to the upper limit with that, i think.

**Comment by chillu** [comment]
I'm making this `impact/medium` since I think its quite an obvious visual inconsistency. It's always bugged me like hell when looking at the CMS UI at least :D

**Comment by chillu** [comment]
@lukereative Might be a good one for you to pick up?

**Comment by kinglozzer** [comment]
TinyMCE width is also a bit odd. It seems to be a percentage of the screen width, but a different percentage to the rest of the fields. So it grows like other fields do, but at a different rate:

<img width="1200" alt="screen shot 2018-02-02 at 09 13 53" src="https://user-images.githubusercontent.com/1655548/35725513-8447350a-07f9-11e8-987f-bfc1aa6e3d1e.png">

<img width="1200" alt="screen shot 2018-02-02 at 09 14 20" src="https://user-images.githubusercontent.com/1655548/35725517-86927b9e-07f9-11e8-9bd1-f1b79f0e5b36.png">

**Comment by newleeland** [comment]
# Possible solution

## Varying widths of forms

Uneven form elements (readonly, dropdowns, treedropdowns): Make fields same length
![screen_shot_2018-02-15_at_2_40_58_pm](https://user-images.githubusercontent.com/8085295/36237163-33316aa8-125f-11e8-9aa7-47812687ebe3.png)
Might be worth removing the max-width from the child elements and leaving the parent to apply it.

## Media query examples

### (min-width: 1200px)
![screen_shot_2018-02-15_at_12_02_34_pm](https://user-images.githubusercontent.com/8085295/36238404-42e45fac-1267-11e8-9fdc-f11e6bdd3d45.png)

(min-width: 1600px)
We potential could change our "xxl" media query variable from 1400px to 1600px. As it not used anywhere else (TBC)
![screen_shot_2018-02-15_at_11_47_56_am](https://user-images.githubusercontent.com/8085295/36238463-89cd87d6-1267-11e8-920c-cd1aa114152a.png)

(min-width: 1900px)
1900 seems like it would need to be specified in the stylesheet rather than using a grid-breakpoint variable
![screen_shot_2018-02-15_at_11_56_06_am](https://user-images.githubusercontent.com/8085295/36238524-02f70416-1268-11e8-81d7-9edbf785fc54.png)
