### ISSUE TITLE
Finding a cross-browser way of detecting component resize

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#595]
Some of our modules use [react-resize-aware](https://www.npmjs.com/package/react-resize-aware) to detect size change in specific component:
* `campaign-admin` use it already ;
* `versioned-admin` has a PR open against it that needs it ;
* `admin` will need something like that for the search tags.

Unfortunately, this package has a [bug that prevents it from working with Firefox](https://github.com/FezVrasta/react-resize-aware/issues/15). I had a quick look to see if it was something I could easily fix myself with a PR, but at first glance I don't think it would be possible.

There's a `ResizeObserver` proposed API which is already [available in Chrome](https://developers.google.com/web/updates/2016/10/resizeobserver). There's a [ResizeObserver Polyfill](https://www.npmjs.com/package/resize-observer-polyfill) which seems to be much better supported than `react-resize-aware`. 

# Possible solutions
* We could switch to using the polyfill and remove all reference to react-resize-aware.
* We could try to fix `react-resize-aware` and do a PR.
* We could re-implement react-resize-aware using the polyfill.
* We could switch to a different solution like [react-resize-observer](https://www.npmjs.com/package/react-resize-observer).

**Comment by chillu** [comment]
From a high level perspective, I would say that resize behaviour should be handled fully handled by media queries. I don't know the details here, so assume in all three cases there's a good reason that's not possible. For the use case of "show tag summary instead of all tags on mobile", I can see how React event hooks are helpful. My assumption is that we can't rely on `document.resize` events because we might change the dimensions within the component without changing the window size, e.g. by collapsing a sidebar.

> We could switch to using the polyfill and remove all reference to react-resize-aware.

This would be my preferred solution, because it'll be the most performant one going forward. Looks like the author of that polyfill has done some performance testing, and it's a small impact on IE. Please cross-browser test this a bit.

**Comment by maxime-rainville** [comment]
I totally agree we should prefer media queries where possible.

I didn't dig too deep to see what `react-resize-aware` does in version-admin or campaign admin, but I don't think it's use so much that switching to `ResizeObserver` would be a big deal.

**Comment by maxime-rainville** [comment]
@robbieaverill I've re-implemented ResizeAware with a ResizeObserver in admin. Once it's out, you should be able to swap the import statement and it should just work.

https://github.com/open-sausages/silverstripe-admin/commit/6eed0bb7eb6037a8305e567c5aa2fad2291311fa

**Comment by chillu** [comment]
This is implemented is `silverstripe/admin` now it seems.

**Comment by maxime-rainville** [comment]
It's still being used in Campaign-admin and Versioned-admin. The one I implemented uses exactly the same API, so it should just be drop-in replacement.

**Comment by robbieaverill** [comment]
I think we recently patched campaign-admin and versioned-admin to use the polyfill since they weren't working in Firefox. Ideally we'd remove the polyfill and update the underlying library which is allegedly fixed to support Firefox now. Can we close this issue for now, or repurpose it?

Related PRs: https://github.com/silverstripe/silverstripe-campaign-admin/pull/141 https://github.com/silverstripe/silverstripe-versioned-admin/pull/108

**Comment by maxime-rainville** [comment]
I think we should keep [resize-observer-polyfill](https://www.npmjs.com/package/resize-observer-polyfill) over the [react-resize-aware](https://www.npmjs.com/package/react-resize-aware)

The polyfill is much more widely used (1 million weekly download vs 5000). `react-resize-aware` took for ever to fix that Firefox issue, so the maintainer might not be overly committed to it.

**Comment by chillu** [comment]
@maxime-rainville I'm confused as to what the next step is here. `react-resize-aware` is still used in versioned-admin - should we remove it from there?

**Comment by robbieaverill** [comment]
@chillu campaign-admin and versioned-admin are now using the polyfill instead of the base package. All PRs are merged so I'm going to close.

**Comment by chillu** [comment]
@robbieaverill  https://github.com/silverstripe/silverstripe-versioned-admin/blob/1/package.json#L84 says `react-resize-aware` is still in there as a dep. Maybe it's not used any more, and we just need to remove it?

**Comment by robbieaverill** [comment]
It just needs merging up, I'll do that now.
