### ISSUE TITLE
TinyMCE is re-fetched when multiple HTMLEditorConfigs are used

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-admin#635]
Affected version: 1.2.1

Our project has two different `HTMLEditorConfig` instances - the default `cms` one, and a custom one used on a couple of fields for specific behaviour. When navigating from a UI in the CMS that uses `cms` to one that uses our custom config, a new (identical) version of TinyMCE is generated and fetched, with the name of the custom config in the filename. This doesn't break the interface, but it _does_ generate duplicate items in the Insert Link menu.

To reproduce, clone the default `cms` config to a new custom HTMLEditorConfig in `_config.php` and apply it to a field. Then navigate between the UI containing that field and one containing a field with the default config. Observe two copies of tinymce fetched in the Network tab of your dev tools, and duplicated items in the Insert Link menu.

(Worth checking - is this resolved in the new React-ified version of the field? #628)

## PRs

- [x] https://github.com/silverstripe/silverstripe-admin/pull/721
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8559
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2307
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/861

**Comment by kinglozzer** [comment]
Just noting one workaround for the duplicate link menu items - disabling and then re-enabling the plugins without the paths to the client-side files seems to work:

```php
// In getCMSFields() - assumes the original config is still active
$editorConfig = clone $field->getEditorConfig();
$editorConfig->disablePlugins(['sslinkinternal', 'sslinkanchor', 'sslinkfile']);
$editorConfig->enablePlugins(['sslinkinternal', 'sslinkanchor', 'sslinkfile']);
```

**Comment by robbieaverill** [comment]
We _could_ block all non-current editorconfig `getScriptURL()` calls, but since it's already in the browser because we're switching pages via PJAX I don't think that will help

**Comment by robbieaverill** [comment]
I think we can identify different editor configs with the active identifier key e.g. `cms` or `custom`, then only initialise our custom plugins if they're meant to be in the current identifier's config. Looking into it.

**Comment by robbieaverill** [comment]
So it looks like because both bundles are running and registering the plugins with `TinyMCEActionRegistrar` (our code). The registration of our plugins only happens once per bundle, which is why we see a duplicated set of links but they don't compound to three or four duplicates (they would if you had that many different TinyMCE configs and switched to pages using them).

I tried clearing the actions from this registrar when the editor is unmounted, but this resulted in them not being re-added again because they're only added when the JS bundle first runs.

In this example code:
```php
// Enable insert-link to internal pages
TinyMCEConfig::get('cms')
    ->enablePlugins([
        'sslinkinternal' => $module
            ->getResource('client/dist/js/TinyMCE_sslink-internal.js'),
        'sslinkanchor' => $module
            ->getResource('client/dist/js/TinyMCE_sslink-anchor.js'),
    ]);
```

These plugin URLs are correctly being associated with the config for each editor, and you can differentiate them by adding in `$settings['config_identifier'] = self::get_active_identifier();` into `TinyMCEConfig::getConfig()`.

![image](https://user-images.githubusercontent.com/5170590/46547744-2e927080-c8cd-11e8-85a8-43a7be4affdf.png)


Using the identifier and knowing the plugin name, we can conditionally register the plugin with TinyMCE:

```patch
diff --git a/client/src/legacy/TinyMCE_sslink-email.js b/client/src/legacy/TinyMCE_sslink-email.js
index 9e80bac..d59926b 100644
--- a/client/src/legacy/TinyMCE_sslink-email.js
+++ b/client/src/legacy/TinyMCE_sslink-email.js
@@ -134,5 +134,15 @@ jQuery.entwine('ss', ($) => {
 });
 
 // Adds the plugin class to the list of available TinyMCE plugins
-tinymce.PluginManager.add(commandName, (editor) => plugin.init(editor));
+tinymce.PluginManager.add(commandName, (editor) => {
+  // Check that this plugin is enabled for the active TinyMCEConfig
+  const config = window.jQuery(`#${editor.id}`).data('config');
+  if (typeof config.external_plugins[commandName] === 'undefined') {
+    return false;
+  }
+  debugger;
+
+  return plugin.init(editor);
+});
+
 export default plugin;
```

This unfortunately doesn't work because `TinyMCEActionRegistrar` is still rendering the buttons for the plugins since they're defined in the global scope of each JS file (not in a tinymce callback) and so execute as soon as each JS file is loaded in the browser.

I _think_ that fixing this will mean a bit of a refactor of how `TinyMCEActionRegistrar` is implemented, and adding some "active config identifier aware" conditionals like above to the places where we register plugins with TinyMCE.

@flamerohr are you able to provide any high level advice with this?

**Comment by robbieaverill** [comment]
Great to see this over the line, nice work team!
