### ISSUE TITLE
Page search field value encoding issue

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-admin#636]
Version: `"silverstripe/recipe-cms": "^4.2.0" (115bbbb5f98f98ea1f18f0d3ddb260a9328359be)`

When I pass a search value via a text field that contains `+` sign, it gets replaced by space.

Input value:

`L + J`

value passed to get param:

`L+++J`

expected value to be passed to get param:

`L+%2B+J`

value shown in the form after search:

`L<space><space><space>J` where `<space>` represents one space character

extected value to be present in the form after search:

`L + J`

We found this changeset which is very suspicious.

https://github.com/silverstripe/silverstripe-admin/commit/050f63c4cb11caada9cca617f35718fba1cb67fc

It's intentionally replacing the correct encoded value of `+` with an unencoded version of the `+`. See code here:

`paramStr = $.param( newParams ).replace(/\%2B/g, '+')`

It's also worth noting that there are two different places where encoding is handled which is again very questionable.

https://github.com/silverstripe/silverstripe-admin/blob/ad18c29866b21fc244822e317175f6c0bfdc9cb9/client/src/legacy/LeftAndMain.js#L1257

https://github.com/silverstripe/silverstripe-admin/blob/master/client/src/legacy/sspath.js#L168

The encoding should be applied only once and properly, not patched on two different places.

# Pull Request
* [ ] https://github.com/silverstripe/silverstripe-admin/pull/667

**Comment by mfendeksilverstripe** [comment]
Added related issue:

https://github.com/silverstripe/silverstripe-admin/issues/410

**Comment by robbieaverill** [comment]
I've read through #410 which introduced the issue originally. [The justification](https://github.com/silverstripe/silverstripe-admin/issues/410#issuecomment-365437664) for replacing encoded + symbols with regular + symbols is that sspath.js is encoding + symbols too early, so this fix was designed to undo that behaviour (instead of patching the jQuery library that provides `$.params`).

The problem is that we have also taken out the ability to use legitimate + symbols in the search string by doing this.

I think perhaps we need to undo the change from #410 and replace the code with something else that will allow + symbols in the URL and encode them at the correct point.

**Comment by robbieaverill** [comment]
This is also reproducible with the new search interface in SS 4.3, which doesn't use the legacy entwine code (AFAIK)

**Comment by robbieaverill** [comment]
PR at #667 for consideration
