### ISSUE TITLE
New UX insert link dialog - Insert anchors

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-admin#65]
Follow up task from https://github.com/silverstripe/silverstripe-framework/issues/6740

## Acceptance Criteria

 * I can insert an anchor into the CMS rich text editor
 * I can choose from existing anchors both on the current page, and another page
 * By default, the current page is selected
 * I can add a custom anchor
 * I can set a link description (prepopulated to selected text)
 * I can edit an existing anchor link by placing the cursor in the link and using the "insert" dialog
 * I can choose to open the anchor in a new window/tab

## Notes

 * Designs: https://projects.invisionapp.com/share/BGAYOTRFY#/screens/224873109

## Related

 * [Inline edit/remove of links in HTML editor](https://github.com/silverstripe/silverstripe-admin/issues/66)
 * [New UX insert link dialog - internal URLs](https://github.com/silverstripe/silverstripe-framework/issues/6740)
 
## PRs

 - [x] https://github.com/silverstripe/silverstripe-admin/pull/255
 - [ ] https://github.com/silverstripe/silverstripe-cms/pull/1966

**Comment by tractorcow** [comment]
Won't be able to get this done in time for beta3. Moved to next milestone.

WIP at https://github.com/open-sausages/silverstripe-cms/tree/pulls/4.0/anchor-modal

**Comment by tractorcow** [comment]
@clarkepaul question about the designs; I have spoken with @flamerohr and he suggested to look into a new approach.

Instead of a dropdown + textfield approach, could we use a single comobox (typeable dropdown) as a means of selecting an existing / creating a new value.

Change:

![image](https://user-images.githubusercontent.com/936064/30404369-873d77de-993a-11e7-903b-932b0e920fb6.png)

To:

![image](https://user-images.githubusercontent.com/936064/30404407-a9783898-993a-11e7-8a30-62564ecda807.png)

A demo of how the combobox could work can be tested at https://jedwatson.github.io/react-select/ (bottom of page, select single select).

**Comment by clarkepaul** [comment]
Yeah that would be good if it was possible. I thought we didn't have that UI possibility though as I already asked for this pattern to be introduced for adding items to campaigns (select or add new) but I was told it was too hard to do, I think @flamerohr said it was too hard to do.

**Comment by clarkepaul** [comment]
Thought it might be good to add this related issue as we were going to use the same approach as mentioned above but either we didn't have time to implement or wasn't quite appropriate at the time. @flamerohr has some tips for implementation also https://github.com/silverstripe/silverstripe-admin/issues/161#issuecomment-318969298

If we do use this functionality then we could retrospectively update the "add to campaign" to follow the same pattern?

**Comment by flamerohr** [comment]
I believe the reason I had suggested it was too hard was because the campaigns would be mixing types of data - IDs (number) with `Name of new campaign` (string)
the anchor work is just string for new or existing, so it's much easier to deal with

**Comment by tractorcow** [comment]
Feedback from review is implemented.
