### ISSUE TITLE
Pressing enter when editing a record in ModelAdmin opens search screen

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#666]
**Version: SS 4.3.x-dev**

When in a model admin and clicking through to create a new managed record, enter a value in a text field and press enter - the form should save, but instead the search form pops up.

* Could be related to https://github.com/silverstripe/silverstripe-cms/issues/2251 since the field names for Title are the same

#### PR's

- [x] https://github.com/silverstripe/silverstripe-framework/pull/8483
- [x] https://github.com/silverstripe/silverstripe-admin/pull/692/

**Comment by chillu** [comment]
@lukereative This breaks accessibility in a primary CMS UI - related to your search work?

**Comment by lukereative** [comment]
FWIW it doesn't submit on 4.2 clean install – just 'loads' and does nothing, seems to be related to: https://github.com/silverstripe/silverstripe-admin/blob/553cffe5ddf5bfbf7ebbe0dd03e3afd423b4f6bf/client/src/legacy/LeftAndMain.EditForm.js#L196-L211 which mentions that the browser will end up picking a random button, which now happens to be the search instead of seemingly nothing.
