### ISSUE TITLE
React Search DropDown's empty string polutes search criteria

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-admin#702]
If you have a Search filter with a DropdownField and you select the _empty_ option, it will sometime get picked up as a search criteria. It should be ignored.

# Steps to reproduce
If you have framework test installed:
* Access the Employee model admin.
* Open the search.
* Open the advanced filters, without selecting anything, and submit the search. Your search results will just reload.
* Open the advanced filters, without selecting anything, and submit the search. 

This time you won't get any results. If you open the search again, you'll notice that there's a `Category` tag with the value set to `all`.

https://youtu.be/m23oIdYu0wg

# Pull Requests
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8504

**Comment by robbieaverill** [comment]
Thanks for the clear steps to reproduce!

**Comment by robbieaverill** [comment]
The PR fixes the bug reported, but I'm also finding that advanced filters don't seem to be filtering:

* Open Employees
* Search without advanced filters for Moses (see 2 results)
* Open advanced filters and add Company Name starting with "Auchan" and search again
* Expect to see one Moses, actually see two

FYI @maxime-rainville, not sure if there are other bugs still you're fixing with search but just a gentle ping. This issue is fixed though.

**Comment by robbieaverill** [comment]
Ignore the last comment, I've now seen the other search bug issues
