### ISSUE TITLE
SS4. Minor. $menu_icon in ModelAdmin subclass not loading correct icon.

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-admin#786]
Setting `$menu_icon` in a subclass of ModelAdmin changes the menu icon but not to the one specified; the default stacked disks icon gets replaced with an icon of a circle containing a star, not by the one I specify. 

There was an early issue in SS4 beta here: https://github.com/silverstripe/silverstripe-admin/pull/311

I am following the usage in https://www.silverstripe.org/learn/lessons/v4/introduction-to-modeladmin-1 and using `private static $menu_icon = 'icons/property.png'`. I have tried this path as well as many others in `public` and in `app` and the correct icon isn't loading.

**Comment by ScopeyNZ** [comment]
Thanks for the report @SpiritLevel . Would you mind sharing the version of SilverStripe you are using?

**Comment by SpiritLevel** [comment]
@ScopeyNZ Hi. I'm using SS4.2.2. `$menu_icon` worked in a previous version of SS4, I just can't remember which :)

**Comment by ScopeyNZ** [comment]
Thanks @SpiritLevel . I was asking partially because there's been an update to `$menu_icon` recently: https://github.com/silverstripe/silverstripe-admin/pull/763 . 

I think this will directly address the problem you've described but unfortunately the fix was targeted at the next minor (4.4). It seems to me like we could backport this for the next patch version of 4.2/4.3 though. Is it possible to confirm if that patch fixes your issue?

**Comment by ScopeyNZ** [comment]
Oh nevermind, I just read through that PR and I saw I already asked for it on the `4.2` branch 😂 : https://github.com/silverstripe/silverstripe-admin/pull/770 .

Can you let me know if the 4.2 development branch (`4.2.x`) has the issue?

**Comment by SpiritLevel** [comment]
@ScopeyNZ Icon problem solved in 4.2.x (which pulled in 4.2.3). Thanks :)
