### ISSUE TITLE
PopoverOptionSet doesn't deal well with long button labels

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-admin#823]
### Affected Version:

1.3.x

### Steps to reproduce

Add a `PopoverOptionSet` component but make one of the button labels really long.

Observe:

![image](https://user-images.githubusercontent.com/3260989/52674936-fc370500-2f89-11e9-943d-4d09b33682eb.png)

### Related issue:

https://github.com/dnadesign/silverstripe-elemental/issues/639

**Comment by ScopeyNZ** [comment]
This was just raised on `dnadesign/silverstripe-elemental`: https://github.com/dnadesign/silverstripe-elemental/issues/639

That issue has some more images of the flawed behaviour and some suggested workarounds.

**Comment by clarkepaul** [comment]
Raised the impact rating as its a high use feature and low effort, especially when all labels are long its a complete mess.

**Comment by korthjp17** [comment]
I think this sort of got fixed (it may be with the newer version of bootstrap (https://github.com/silverstripe/silverstripe-admin/pull/849) because the buttons were also having the same issue by default in BS4)

However, now it seems there is a slightly different issue. There is a max-height set to these for 40px, so now that the text can wrap, some of these items aren't tall enough.

![image](https://user-images.githubusercontent.com/3858661/58110199-b2773f80-7bb4-11e9-98ed-f7413c04aa25.png)

I could look into doing a PR to fix the max-height issue, but not 100% sure where this style is getting pulled from.

**Comment by clarkepaul** [comment]
@Cheddam @ScopeyNZ one of you had a fix for this coming through from memory, did this happen by chance?

**Comment by Cheddam** [comment]
@clarkepaul Yep, I have a PR 95% ready, will be up soon.

**Comment by ScopeyNZ** [comment]
Closed in #882
