### ISSUE TITLE
Can't edit related objects when sorting ModelAdmin

### ISSUE THREAD

**Issue by altwohill** [silverstripe/silverstripe-admin#887]
Version: 1.x-dev (a5588972f4b35e38a8a4e157b82e2955fbabccf4)

This doesn't affect 1.3.3

Consider this gist: https://gist.github.com/altwohill/e2211bc80a52dbbce360f57603fb1e91

If I create two breeds with dogs in each, then sort the breeds in ModelAdmin, I can no longer edit the dogs, as the `ORDER BY` clause is added in.

> [Emergency] Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query: SELECT "Dog"."ID", "BreedName" FROM "Dog" WHERE ("Dog"."BreedID" = ?) ORDER BY "BreedName" ASC LIMIT 17 Unknown column 'BreedName' in 'field list'

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/9072

**Comment by maxime-rainville** [comment]
Manage to replicate the error using @altwohill's example.

# Steps to reproduce
* Create a Breed.
* Create a Dog for the Breed you just created.
* Return to the Breed ModelAmin
* Sort the ModelAdmin by Breed Name
* Access the Breed.
* Try to edit the Dog
* Get a 500 error with malformed MySQL.

Expected behaviour: you get a Form to edit the Dog.

https://youtu.be/R_SUfgPFDt0

# Possible problem
My guess is this that we're tracking the sort order from the top level GridField so we can restore it later on. This sort order must be applied to the query to retrieve the child records, even if you are looking at a different Model.

@bergice This might be related to the better buttons

**Comment by unclecheese** [comment]
The issue appears to be that the `gridState` is applied globally, when it should be namespaced to the gridfield it applies to.

**Comment by bergice** [comment]
> The issue appears to be that the `gridState` is applied globally, when it should be namespaced to the gridfield it applies to.

Yep, can confirm this is the issue.
