### ISSUE TITLE
TreeDropdownField: Fails to load items when TreeBaseID is set

### ISSUE THREAD

**Issue by flashbackzoo** [silverstripe/silverstripe-admin#954]
Version: 1.4.2

When using `TreeDropdownField` with `setTreeBaseID` child items fail to load e.g.

```php
public function getCMSFields()
{
    $fields = parent::getCMSFields();

    $myBaseID = 3;

    $fields->addFieldToTab(
        'Root.Main',
        TreeDropdownField::create(
            'NestedObjectID',
            'Nested Object',
            NestedObject::class
        )
        ->setTreeBaseID($myBaseID)
    );

    return $fields;
}
```

__Steps to reproduce__

1. Expand the "Nested Object" dropdown
2. Show children of an item by clicking the right arrow button

__Expected__
The item expands, showing child items.

__Actual__
An XHR request is send, the response comes back, but the items are not loaded and the field becomes un-selectable.

I've put together this example including Vagrantfile and sspak.
https://github.com/flashbackzoo/ss4-treedropdownfield-baseid-bug

# Pull request
- [x] https://github.com/silverstripe/silverstripe-framework/pull/9743/
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/1144

**Comment by maxime-rainville** [comment]
I haven't tried the vagrant box yet.

Are you getting anything in the error logs or browser console?

**Comment by flashbackzoo** [comment]
There's no error in the browser console. The network tab shows the request being send, the response comes back with the expected data, but it's not loaded into the component for some reason.

**Comment by kinglozzer** [comment]
Still an issue in 1.6.4, I’m experiencing the exact same issue: the AJAX queries for the field return the expected child items, but they never actually get rendered by the React component. It’s displaying “No results found” instead of “No children”, so it’s definitely not passing through our `TreeDropdownFieldMenu` component. Inspecting the HTML also leads me to that conclusion: it’s rendering the default `react-select` search results, even when a search hasn’t been performed.

<img width="755" alt="Screenshot 2020-10-22 at 13 03 28" src="https://user-images.githubusercontent.com/1655548/96869663-b07b7500-1467-11eb-9cad-70155243595e.png">

**Comment by xini** [comment]
any updates on getting these RSs merged? thanks.
